'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.secondaryBG = exports.lineColor = exports.secondaryText = exports.background = exports.uniswap = exports.redditColor = exports.lightBorder = exports.lightGrey = exports.dividerBg = exports.twitterBlue = exports.warningA = exports.warning = exports.errorA = exports.error = exports.gold = exports.red = exports.green = exports.modalBackground = exports.lightGreyBg = exports.white = exports.black = exports.grey = exports.blue = void 0;
var lightTheme = true;
var gs = function gs(n) {
  return 'hsl(0, 0%, '.concat(n, '%)');
};
var gsa = function gsa(n, a) {
  return 'hsla(0, 0%, '.concat(n, '%, ').concat(a, ')');
};
var blue = lightTheme ? '#0000ff' : '#0088ff';
exports.blue = blue;
var grey = lightTheme ? gs(50) : gs(50);
exports.grey = grey;
var black = lightTheme ? gs(0) : gs(100);
exports.black = black;
var white = lightTheme ? gs(100) : gs(8);
exports.white = white;
var lightGreyBg = lightTheme ? gs(98) : gs(7);
exports.lightGreyBg = lightGreyBg;
var modalBackground = lightTheme ? gsa(100, 0.7) : gsa(0, 0.7);
exports.modalBackground = modalBackground;
var green = '#7ED321';
exports.green = green;
var red = '#D0021B';
exports.red = red;
var gold = '#FFC864';
exports.gold = gold;
var error = 'hsl(0, 66%, 45%)';
exports.error = error;
var errorA = 'hsla(33, 66%, 45%, .05)';
exports.errorA = errorA;
var warning = 'hsl(33, 93%,54%)';
exports.warning = warning;
var warningA = 'hsla(33, 93%, 54%, .05)';
exports.warningA = warningA;
var twitterBlue = '#00aced';
exports.twitterBlue = twitterBlue;
var dividerBg = lightTheme ? gs(97) : gs(3);
exports.dividerBg = dividerBg;
var lightGrey = lightTheme ? gs(87) : gs(13);
exports.lightGrey = lightGrey;
var lightBorder = lightTheme ? gs(85) : gs(20);
exports.lightBorder = lightBorder;
var redditColor = '#ff4500';
exports.redditColor = redditColor;
var uniswap = 'rgb(220, 107, 229)';
exports.uniswap = uniswap;
var background = white;
exports.background = background;
var secondaryText = grey;
exports.secondaryText = secondaryText;
var lineColor = lightGrey;
exports.lineColor = lineColor;
var secondaryBG = lightGreyBg;
exports.secondaryBG = secondaryBG;
//# sourceMappingURL=colors.js.map
