'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.default = void 0;
var codes =
  '\n  .markdow-body {\n    flex: 1;\n  }\n  .markdown-body code {\n    padding: .2em .4em;\n    margin: 0;\n    font-size: 100%;\n    background-color: rgba(27,31,35,.05);\n    border-radius: 3px;\n  }\n\n  .markdown-body pre {\n    word-wrap: normal;\n  }\n\n  .markdown-body pre>code {\n    padding: 0;\n    margin: 0;\n    font-size: 100%;\n    word-break: normal;\n    white-space: pre;\n    background: transparent;\n    border: 0;\n  }\n\n  .markdown-body .highlight {\n    margin-top: 8px;\n    margin-bottom: 8px;\n  }\n\n  .markdown-body .highlight pre {\n    margin-bottom: 0;\n    word-break: normal;\n  }\n\n  .markdown-body .highlight pre,\n  .markdown-body pre {\n    padding: 16px;\n    overflow: auto;\n    font-size: 100%;\n    line-height: 1.45;\n    background-color: #f6f8fa;\n    border-radius: 3px;\n  }\n\n  .markdown-body pre code {\n    display: inline;\n    max-width: auto;\n    padding: 0;\n    margin: 0;\n    overflow: visible;\n    line-height: inherit;\n    word-wrap: normal;\n    background-color: initial;\n    border: 0;\n  }\n';
var _default = '\n  '.concat(
  codes,
  '\n\n  .markdown-body blockquote {\n    margin: 0;\n  }\n\n  .markdown-body blockquote {\n    padding: 0 1em;\n    color: #6a737d;\n    border-left: .25em solid #dfe2e5;\n  }\n\n\n  .markdown-body ol,\n  .markdown-body ul {\n    padding-left: 0;\n    margin-top: 0;\n    margin-bottom: 0;\n  }\n\n  .markdown-body ol ol,\n  .markdown-body ul ol {\n    list-style-type: lower-roman;\n  }\n\n  .markdown-body ol ol ol,\n  .markdown-body ol ul ol,\n  .markdown-body ul ol ol,\n  .markdown-body ul ul ol {\n    list-style-type: lower-alpha;\n  }\n\n  .markdown-body ol,\n  .markdown-body ul {\n    padding-left: 2em;\n  }\n\n  .markdown-body li {\n    word-wrap: break-all;\n  }\n\n  .markdown-body li>p {\n    margin-top: 16px;\n  }\n\n  .markdown-body li+li {\n    margin-top: .25em;\n  }\n\n  .markdown-body blockquote,\n  .markdown-body details,\n  .markdown-body dl,\n  .markdown-body ol,\n  .markdown-body p,\n  .markdown-body pre,\n  .markdown-body table,\n  .markdown-body div,\n  .markdown-body ul {\n    margin-top: 8px;\n    margin-bottom: 8px;\n  }\n'
);
exports.default = _default;
//# sourceMappingURL=markdown.js.map
