'use strict';
Object.defineProperty(exports, '__esModule', { value: true });
exports.SHOW_MOBILE_PROMPT_AFTER_DAYS = exports.SHOW_DESKTOP_PROMPT_AFTER_DAYS = exports.SHOW_BET_PROMPT_AFTER_DAYS = void 0;
var SHOW_BET_PROMPT_AFTER_DAYS = 14;
exports.SHOW_BET_PROMPT_AFTER_DAYS = SHOW_BET_PROMPT_AFTER_DAYS;
var SHOW_DESKTOP_PROMPT_AFTER_DAYS = 30;
exports.SHOW_DESKTOP_PROMPT_AFTER_DAYS = SHOW_DESKTOP_PROMPT_AFTER_DAYS;
var SHOW_MOBILE_PROMPT_AFTER_DAYS = 21;
exports.SHOW_MOBILE_PROMPT_AFTER_DAYS = SHOW_MOBILE_PROMPT_AFTER_DAYS;
//# sourceMappingURL=notificationTimes.js.map
